import 'babel-polyfill'
import 'webcomponents.js/webcomponents-lite'
// import '@webcomponents/webcomponentsjs/bundles/webcomponents-ce'
// import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter'
import 'coffeekraken-sugar/js/features/all'
import SScrollDownIndicatorComponent from '../../../dist/index'
